-- 운동 기록 기능 DDL (Oracle / MOTIVE 스키마)
-- motive-ui 프로필 > 운동 기록 화면(app/profile/record) 기준으로 작성
-- 시퀀스 채번 방식 채택 (기존 Auth-mapper.xml의 USERS_SEQ/SOCIAL_SEQ 패턴과 동일)
-- 백엔드(kr.co.motive) 반영 전 확인/조정이 필요한 가정은 하단 주석 참고

-- ============================================================
-- EXERCISES: 이미 존재하는 테이블 → REG_DT, MOD_DT만 추가
-- (기존 컬럼: EXERCISE_ID, NAME, BODY_PART_CD, EXERCISE_EQUIPMENT_CD, IMAGE_FILE_ID)
-- ============================================================
ALTER TABLE EXERCISES ADD (
    REG_DT DATE DEFAULT SYSDATE NOT NULL,
    MOD_DT DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN EXERCISES.REG_DT IS '등록일시';
COMMENT ON COLUMN EXERCISES.MOD_DT IS '수정일시';

-- ============================================================
-- 시퀀스
-- ============================================================
CREATE SEQUENCE WORKOUT_RECORD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WORKOUT_RECORD_EXERCISE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WORKOUT_RECORD_SET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 운동 기록 헤더 (날짜/시간, 카테고리, 운동한 시간, 회원번호)
CREATE TABLE WORKOUT_RECORD (
    WORKOUT_RECORD_ID   NUMBER         NOT NULL,   -- WORKOUT_RECORD_SEQ 채번
    USER_ID             NUMBER         NOT NULL,
    CATEGORY_CD         VARCHAR2(20)   NOT NULL,   -- 헬스/홈트/러닝/등산/야외
    RECORD_DT           DATE           NOT NULL,   -- 날짜 및 시간
    DURATION_MIN        NUMBER DEFAULT 0 NOT NULL, -- 운동한 시간(분) = 시간*60+분으로 환산해 저장
    REG_DT              DATE DEFAULT SYSDATE NOT NULL,
    MOD_DT              DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_WORKOUT_RECORD PRIMARY KEY (WORKOUT_RECORD_ID),
    CONSTRAINT FK_WORKOUT_RECORD_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

COMMENT ON TABLE WORKOUT_RECORD IS '운동 기록 헤더';
COMMENT ON COLUMN WORKOUT_RECORD.WORKOUT_RECORD_ID IS '운동기록아이디';
COMMENT ON COLUMN WORKOUT_RECORD.USER_ID IS '회원아이디';
COMMENT ON COLUMN WORKOUT_RECORD.CATEGORY_CD IS '카테고리코드(헬스/홈트/러닝/등산/야외)';
COMMENT ON COLUMN WORKOUT_RECORD.RECORD_DT IS '기록일시';
COMMENT ON COLUMN WORKOUT_RECORD.DURATION_MIN IS '운동시간(분)';
COMMENT ON COLUMN WORKOUT_RECORD.REG_DT IS '등록일시';
COMMENT ON COLUMN WORKOUT_RECORD.MOD_DT IS '수정일시';

-- 상세기록: 기록 1건에 딸린 운동들
CREATE TABLE WORKOUT_RECORD_EXERCISE (
    WORKOUT_RECORD_EXERCISE_ID  NUMBER NOT NULL,   -- WORKOUT_RECORD_EXERCISE_SEQ 채번
    WORKOUT_RECORD_ID           NUMBER NOT NULL,
    EXERCISE_ID                 NUMBER NOT NULL,
    SORT_NO                     NUMBER DEFAULT 0 NOT NULL,  -- 상세기록 내 운동 순서
    CONSTRAINT PK_WORKOUT_RECORD_EXERCISE PRIMARY KEY (WORKOUT_RECORD_EXERCISE_ID),
    CONSTRAINT FK_WRE_RECORD   FOREIGN KEY (WORKOUT_RECORD_ID) REFERENCES WORKOUT_RECORD (WORKOUT_RECORD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WRE_EXERCISE FOREIGN KEY (EXERCISE_ID)       REFERENCES EXERCISES (EXERCISE_ID)
);

COMMENT ON TABLE WORKOUT_RECORD_EXERCISE IS '운동 기록 상세(기록별 운동 목록)';
COMMENT ON COLUMN WORKOUT_RECORD_EXERCISE.WORKOUT_RECORD_EXERCISE_ID IS '상세기록아이디';
COMMENT ON COLUMN WORKOUT_RECORD_EXERCISE.WORKOUT_RECORD_ID IS '운동기록아이디(FK)';
COMMENT ON COLUMN WORKOUT_RECORD_EXERCISE.EXERCISE_ID IS '운동아이디(FK)';
COMMENT ON COLUMN WORKOUT_RECORD_EXERCISE.SORT_NO IS '상세기록 내 운동 정렬순서';

-- 운동별 세트 (중량/횟수)
CREATE TABLE WORKOUT_RECORD_SET (
    WORKOUT_RECORD_SET_ID       NUMBER NOT NULL,   -- WORKOUT_RECORD_SET_SEQ 채번
    WORKOUT_RECORD_EXERCISE_ID  NUMBER NOT NULL,
    SET_NO                      NUMBER NOT NULL,           -- 1세트, 2세트...
    WEIGHT                      NUMBER(6,2) DEFAULT 0 NOT NULL,  -- kg
    REPS                        NUMBER DEFAULT 0 NOT NULL,       -- 회
    CONSTRAINT PK_WORKOUT_RECORD_SET PRIMARY KEY (WORKOUT_RECORD_SET_ID),
    CONSTRAINT FK_WRS_EXERCISE FOREIGN KEY (WORKOUT_RECORD_EXERCISE_ID)
        REFERENCES WORKOUT_RECORD_EXERCISE (WORKOUT_RECORD_EXERCISE_ID) ON DELETE CASCADE
);

COMMENT ON TABLE WORKOUT_RECORD_SET IS '운동 기록 세트(중량/횟수)';
COMMENT ON COLUMN WORKOUT_RECORD_SET.WORKOUT_RECORD_SET_ID IS '세트기록아이디';
COMMENT ON COLUMN WORKOUT_RECORD_SET.WORKOUT_RECORD_EXERCISE_ID IS '상세기록아이디(FK)';
COMMENT ON COLUMN WORKOUT_RECORD_SET.SET_NO IS '세트번호';
COMMENT ON COLUMN WORKOUT_RECORD_SET.WEIGHT IS '중량(kg)';
COMMENT ON COLUMN WORKOUT_RECORD_SET.REPS IS '횟수(회)';

CREATE INDEX IX_WORKOUT_RECORD_USER ON WORKOUT_RECORD (USER_ID, RECORD_DT);
CREATE INDEX IX_WRE_RECORD ON WORKOUT_RECORD_EXERCISE (WORKOUT_RECORD_ID);
CREATE INDEX IX_WRS_EXERCISE ON WORKOUT_RECORD_SET (WORKOUT_RECORD_EXERCISE_ID);

-- ============================================================
-- 확인/조정이 필요한 가정
-- ============================================================
-- 1. PK/시퀀스: WORKOUT_RECORD, WORKOUT_RECORD_EXERCISE, WORKOUT_RECORD_SET는
--    IDENTITY 대신 <테이블명>_SEQ 시퀀스로 채번한다고 가정 (기존 USERS_SEQ/SOCIAL_SEQ/
--    CMM_FILE_SEQ와 동일한 패턴). MyBatis insert에서 <selectKey order="BEFORE">로
--    SEQ.NEXTVAL을 미리 받아 채우는 방식(Auth-mapper.xml의 insertUser 참고).
-- 2. USERS FK: 실제 PK 컬럼은 USER_ID (Auth-mapper.xml 기준, ID 아님) — 반영 완료.
-- 3. EXERCISES FK: 실제 PK 컬럼은 EXERCISE_ID (Exercise-mapper.xml 기준) — 반영 완료.
-- 4. CATEGORY_CD / BODY_PART_CD / EQUIPMENT_CD: 지금은 단순 VARCHAR2인데,
--    kr.co.motive.code 쪽에 공통코드 테이블이 있다면 그 코드 그룹으로
--    옮기는 게 나을 수 있음 (프론트 features/common/commonCode.ts 패턴과 대응).
-- 5. DURATION_MIN: 화면은 시/분 두 입력이지만 분 단위로 합쳐서 저장.
--    시/분을 그대로 남기고 싶으면 컬럼을 둘로 분리 가능.
